add geoweaver
pditommaso/awesome-pipeline pull request #201
Opened 2024-09-09 01:39 UTC by manuel-g-castro

2024-09-09 08:18 UTC, pditommaso requested changes
Thanks for contributing this. As long as it has a backend server, better to add it in the [Workflow platforms](https://github.com/pditommaso/awesome-pipeline?tab=readme-ov-file#workflow-platforms) section

2024-09-10 00:26 UTC, manuel-g-castro commented
Thank you for replying! Sure, just did it.

2024-09-10 06:30 UTC, pditommaso approved these changes

2024-09-10 06:30 UTC, merged

2024-09-10 06:30 UTC, pditommaso commented
Thanks